export enum ElementType {
    AUTO_COMPLETE = 'auto-complete',
    BUTTON_GROUP = 'button-group',
    CALENDAR = 'calendar',
    CHECKBOX = 'checkbox',
    COLOR_PICKER = 'color-picker',
    COMPONENT = 'component',
    CONTAINER = 'container',
    DROPDOWN = 'dropdown',
    GENERAL = 'general',
    HTML_EDITOR = 'html-editor',
    IMAGE = 'image',
    INPUT_NUMBER = 'input-number',
    INPUT_SWITCH = 'input-switch',
    INPUT_TEXT = 'input-text',
    KNOB = 'knob',
    MULTI_SELECT = 'multi-select',
    RADIO_BUTTON = 'radio-button',
    SELECT = 'select',
    SELECT_BUTTON = 'select-button',
    SLIDER = 'slider',
    SPLIT_BUTTON = 'split-button',
    TEXT_AREA = 'text-area',
    TEXT_BLOCK = 'text-block',
    TOGGLE_BUTTON = 'toggle-button',
}