import { CharMap } from 'warskald-ui/models';

export const IpaMapping: CharMap[] = [
    {
        char: 'ɑ',
        decimal: 593,
        hex: '0251',
        tooltip: 'open back unrounded',
    },
    {
        char: 'ɐ',
        decimal: 592,
        hex: '0250',
        tooltip: 'open-mid schwa',
    },
    {
        char: 'ɒ',
        decimal: 594,
        hex: '0252',
        tooltip: 'open back rounded',
    },
    {
        char: 'æ',
        decimal: 230,
        hex: '00E6',
        tooltip: 'raised open front unrounded',
    },
    {
        char: 'ɓ',
        decimal: 595,
        hex: '0253',
        tooltip: 'vd bilabial implosive',
    },
    {
        char: 'ʙ',
        decimal: 665,
        hex: '0299',
        tooltip: 'vd bilabial trill',
    },
    {
        char: 'β',
        decimal: 946,
        hex: '03B2',
        tooltip: 'vd bilabial fricative',
    },
    {
        char: 'ɔ',
        decimal: 596,
        hex: '0254',
        tooltip: 'open-mid back rounded',
    },
    {
        char: 'ɕ',
        decimal: 597,
        hex: '0255',
        tooltip: 'vl alveolopalatal fricative',
    },
    {
        char: 'ç',
        decimal: 231,
        hex: '00E7',
        tooltip: 'vl palatal fricative',
    },
    {
        char: 'ɗ',
        decimal: 599,
        hex: '0257',
        tooltip: 'vd alveolar implosive',
    },
    {
        char: 'ɖ',
        decimal: 598,
        hex: '0256',
        tooltip: 'vd retroflex plosive',
    },
    {
        char: 'ð',
        decimal: 240,
        hex: '00F0',
        tooltip: 'vd dental fricative',
    },
    {
        char: 'ʤ',
        decimal: 676,
        hex: '02A4',
        tooltip: 'vd postalveolar affricate',
    },
    {
        char: 'ə',
        decimal: 601,
        hex: '0259',
        tooltip: 'schwa',
    },
    {
        char: 'ɘ',
        decimal: 600,
        hex: '0258',
        tooltip: 'close-mid schwa',
    },
    {
        char: 'ɚ',
        decimal: 602,
        hex: '025A',
        tooltip: 'rhotacized schwa',
    },
    {
        char: 'ɛ',
        decimal: 603,
        hex: '025B',
        tooltip: 'open-mid front unrounded',
    },
    {
        char: 'ɜ',
        decimal: 604,
        hex: '025C',
        tooltip: 'open-mid central',
    },
    {
        char: 'ɝ',
        decimal: 605,
        hex: '025D',
        tooltip: 'rhotacized open-mid central',
    },
    {
        char: 'ɞ',
        decimal: 606,
        hex: '025E',
        tooltip: 'open-mid central rounded',
    },
    {
        char: 'ɟ',
        decimal: 607,
        hex: '025F',
        tooltip: 'vd palatal plosive',
    },
    {
        char: 'ʄ',
        decimal: 644,
        hex: '0284',
        tooltip: 'vd palatal implosive',
    },
    {
        char: 'ɡ',
        decimal: 609,
        hex: '0261',
        tooltip: 'vd velar plosive (but the IPA has ruled that an ordinary g is also acceptable)',
    },
    {
        char: 'ɠ',
        decimal: 608,
        hex: '0260',
        tooltip: 'vd velar implosive',
    },
    {
        char: 'ɢ',
        decimal: 610,
        hex: '0262',
        tooltip: 'vd uvular plosive',
    },
    {
        char: 'ʛ',
        decimal: 667,
        hex: '029B',
        tooltip: 'vd uvular implosive',
    },
    {
        char: 'ɦ',
        decimal: 614,
        hex: '0266',
        tooltip: 'vd glottal fricative',
    },
    {
        char: 'ɧ',
        decimal: 615,
        hex: '0267',
        tooltip: 'vl multiple-place fricative',
    },
    {
        char: 'ħ',
        decimal: 295,
        hex: '0127',
        tooltip: 'vl pharyngeal fricative',
    },
    {
        char: 'ɥ',
        decimal: 613,
        hex: '0265',
        tooltip: 'labial-palatal approximant',
    },
    {
        char: 'ʜ',
        decimal: 668,
        hex: '029C',
        tooltip: 'vl epiglottal fricative',
    },
    {
        char: 'ɨ',
        decimal: 616,
        hex: '0268',
        tooltip: 'close central unrounded',
    },
    {
        char: 'ɪ',
        decimal: 618,
        hex: '026A',
        tooltip: 'lax close front unrounded',
    },
    {
        char: 'ʝ',
        decimal: 669,
        hex: '029D',
        tooltip: 'vd palatal fricative',
    },
    {
        char: 'ɭ',
        decimal: 621,
        hex: '026D',
        tooltip: 'vd retroflex lateral',
    },
    {
        char: 'ɬ',
        decimal: 620,
        hex: '026C',
        tooltip: 'vl alveolar lateral fricative',
    },
    {
        char: 'ɫ',
        decimal: 619,
        hex: '026B',
        tooltip: 'velarized vd alveolar lateral',
    },
    {
        char: 'ɮ',
        decimal: 622,
        hex: '026E',
        tooltip: 'vd alveolar lateral fricative',
    },
    {
        char: 'ʟ',
        decimal: 671,
        hex: '029F',
        tooltip: 'vd velar lateral',
    },
    {
        char: 'ɱ',
        decimal: 625,
        hex: '0271',
        tooltip: 'vd labiodental nasal',
    },
    {
        char: 'ɯ',
        decimal: 623,
        hex: '026F',
        tooltip: 'close back unrounded',
    },
    {
        char: 'ɰ',
        decimal: 624,
        hex: '0270',
        tooltip: 'velar approximant',
    },
    {
        char: 'ŋ',
        decimal: 331,
        hex: '014B',
        tooltip: 'vd velar nasal',
    },
    {
        char: 'ɳ',
        decimal: 627,
        hex: '0273',
        tooltip: 'vd retroflex nasal',
    },
    {
        char: 'ɲ',
        decimal: 626,
        hex: '0272',
        tooltip: 'vd palatal nasal',
    },
    {
        char: 'ɴ',
        decimal: 628,
        hex: '0274',
        tooltip: 'vd uvular nasal',
    },
    {
        char: 'ø',
        decimal: 248,
        hex: '00F8',
        tooltip: 'front close-mid rounded',
    },
    {
        char: 'ɵ',
        decimal: 629,
        hex: '0275',
        tooltip: 'rounded schwa',
    },
    {
        char: 'ɸ',
        decimal: 632,
        hex: '0278',
        tooltip: 'vl bilabial fricative',
    },
    {
        char: 'θ',
        decimal: 952,
        hex: '03B8',
        tooltip: 'vl dental fricative',
    },
    {
        char: 'œ',
        decimal: 339,
        hex: '0153',
        tooltip: 'front open-mid rounded',
    },
    {
        char: 'ɶ',
        decimal: 630,
        hex: '0276',
        tooltip: 'front open rounded',
    },
    {
        char: 'ʘ',
        decimal: 664,
        hex: '0298',
        tooltip: 'bilabial click',
    },
    {
        char: 'ɹ',
        decimal: 633,
        hex: '0279',
        tooltip: 'vd (post)alveolar approximant',
    },
    {
        char: 'ɺ',
        decimal: 634,
        hex: '027A',
        tooltip: 'vd alveolar lateral flap',
    },
    {
        char: 'ɾ',
        decimal: 638,
        hex: '027E',
        tooltip: 'vd alveolar tap',
    },
    {
        char: 'ɻ',
        decimal: 635,
        hex: '027B',
        tooltip: 'vd retroflex approximant',
    },
    {
        char: 'ʀ',
        decimal: 640,
        hex: '0280',
        tooltip: 'vd uvular trill',
    },
    {
        char: 'ʁ',
        decimal: 641,
        hex: '0281',
        tooltip: 'vd uvular fricative',
    },
    {
        char: 'ɽ',
        decimal: 637,
        hex: '027D',
        tooltip: 'vd retroflex flap',
    },
    {
        char: 'ʂ',
        decimal: 642,
        hex: '0282',
        tooltip: 'vl retroflex fricative',
    },
    {
        char: 'ʃ',
        decimal: 643,
        hex: '0283',
        tooltip: 'vl postalveolar fricative',
    },
    {
        char: 'ʈ',
        decimal: 648,
        hex: '0288',
        tooltip: 'vl retroflex plosive',
    },
    {
        char: 'ʧ',
        decimal: 679,
        hex: '02A7',
        tooltip: 'vl postalveolar affricate',
    },
    {
        char: 'ʉ',
        decimal: 649,
        hex: '0289',
        tooltip: 'close central rounded',
    },
    {
        char: 'ʊ',
        decimal: 650,
        hex: '028A',
        tooltip: 'lax close back rounded',
    },
    {
        char: 'ʋ',
        decimal: 651,
        hex: '028B',
        tooltip: 'vd labiodental approximant',
    },
    {
        char: 'ⱱ',
        decimal: 11377,
        hex: '2C71',
        tooltip: 'voiced labiodental flap',
    },
    {
        char: 'ʌ',
        decimal: 652,
        hex: '028C',
        tooltip: 'open-mid back unrounded',
    },
    {
        char: 'ɣ',
        decimal: 611,
        hex: '0263',
        tooltip: 'vd velar fricative',
    },
    {
        char: 'ɤ',
        decimal: 612,
        hex: '0264',
        tooltip: 'close-mid back unrounded',
    },
    {
        char: 'ʍ',
        decimal: 653,
        hex: '028D',
        tooltip: 'vl labial-velar fricative',
    },
    {
        char: 'χ',
        decimal: 967,
        hex: '03C7',
        tooltip: 'vl uvular fricative',
    },
    {
        char: 'ʎ',
        decimal: 654,
        hex: '028E',
        tooltip: 'vd palatal lateral',
    },
    {
        char: 'ʏ',
        decimal: 655,
        hex: '028F',
        tooltip: 'lax close front rounded',
    },
    {
        char: 'ʑ',
        decimal: 657,
        hex: '0291',
        tooltip: 'vd alveolopalatal fricative',
    },
    {
        char: 'ʐ',
        decimal: 656,
        hex: '0290',
        tooltip: 'vd retroflex fricative',
    },
    {
        char: 'ʒ',
        decimal: 658,
        hex: '0292',
        tooltip: 'vd postalveolar fricative',
    },
    {
        char: 'ʔ',
        decimal: 660,
        hex: '0294',
        tooltip: 'glottal plosive',
    },
    {
        char: 'ʡ',
        decimal: 673,
        hex: '02A1',
        tooltip: 'vd epiglottal plosive',
    },
    {
        char: 'ʕ',
        decimal: 661,
        hex: '0295',
        tooltip: 'vd pharyngeal fricative',
    },
    {
        char: 'ʢ',
        decimal: 674,
        hex: '02A2',
        tooltip: 'vd epiglottal fricative',
    },
    {
        char: 'ǀ',
        decimal: 448,
        hex: '01C0',
        tooltip: 'dental click',
    },
    {
        char: 'ǁ',
        decimal: 449,
        hex: '01C1',
        tooltip: 'alveolar lateral click',
    },
    {
        char: 'ǂ',
        decimal: 450,
        hex: '01C2',
        tooltip: 'alveolar click',
    },
    {
        char: 'ǃ',
        decimal: 451,
        hex: '01C3',
        tooltip: 'retroflex click',
    },
];