import { ElementRef, TemplateRef } from '@angular/core';

export interface PCalendarConfig {
    iconDisplay?: 'input' | 'button';
    style?: { [klass: string]: unknown } | null | undefined;
    styleClass?: string | undefined;
    inputStyle?: { [klass: string]: unknown } | null | undefined;
    inputId?: string | undefined;
    name?: string | undefined;
    inputStyleClass?: string | undefined;
    placeholder?: string | undefined;
    ariaLabelledBy?: string | undefined;
    ariaLabel?: string | undefined;
    iconAriaLabel?: string | undefined;
    disabled?: boolean | undefined;
    dateFormat?: string | undefined;
    multipleSeparator?: string;
    rangeSeparator?: string;
    inline?: boolean;
    showOtherMonths?: boolean;
    selectOtherMonths?: boolean | undefined;
    showIcon?: boolean | undefined;
    icon?: string | undefined;
    appendTo?: HTMLElement | ElementRef | TemplateRef<unknown> | string | null | undefined | unknown;
    readonlyInput?: boolean | undefined;
    shortYearCutoff?: unknown;
    monthNavigator?: boolean | undefined;
    yearNavigator?: boolean | undefined;
    hourFormat?: string;
    timeOnly?: boolean | undefined;
    stepHour?: number;
    stepMinute?: number;
    stepSecond?: number;
    showSeconds?: boolean;
    required?: boolean | undefined;
    showOnFocus?: boolean;
    showWeek?: boolean;
    startWeekFromFirstDayOfYear?: boolean;
    showClear?: boolean;
    dataType?: string;
    selectionMode?: 'single' | 'multiple' | 'range' | undefined;
    maxDateCount?: number | undefined;
    showButtonBar?: boolean | undefined;
    todayButtonStyleClass?: string;
    clearButtonStyleClass?: string;
    autofocus?: boolean | undefined;
    autoZIndex?: boolean;
    baseZIndex?: number;
    panelStyleClass?: string | undefined;
    panelStyle?: unknown;
    keepInvalid?: boolean;
    hideOnDateTimeSelect?: boolean;
    touchUI?: boolean | undefined;
    timeSeparator?: string;
    focusTrap?: boolean;
    showTransitionOptions?: string;
    hideTransitionOptions?: string;
    tabindex?: number | undefined;
    variant?: 'filled' | 'outlined';

    [key: string]: unknown;
}
