import { ElementRef, TemplateRef } from '@angular/core';
import { ScrollerOptions, OverlayOptions } from 'primeng/api';

export interface PMultiSelectConfig {
    id?: string | undefined;
    ariaLabel?: string | undefined;
    style?: { [klass: string]: unknown } | null | undefined;
    styleClass?: string | undefined;
    panelStyle?: unknown;
    panelStyleClass?: string | undefined;
    inputId?: string | undefined;
    disabled?: boolean | undefined;
    readonly?: boolean | undefined;
    group?: boolean | undefined;
    filter?: boolean;
    filterPlaceHolder?: string | undefined;
    filterLocale?: string | undefined;
    overlayVisible?: boolean | undefined;
    tabindex?: number | undefined;
    variant?: 'filled' | 'outlined';
    appendTo?: HTMLElement | ElementRef | TemplateRef<unknown> | string | null | undefined | unknown;
    dataKey?: string | undefined;
    name?: string | undefined;
    ariaLabelledBy?: string | undefined;
    selectionLimit?: number | undefined;
    selectedItemsLabel?: string | undefined;
    showToggleAll?: boolean;
    emptyFilterMessage?: string;
    emptyMessage?: string;
    resetFilterOnHide?: boolean;
    dropdownIcon?: string | undefined;
    optionLabel?: string | undefined;
    optionValue?: string | undefined;
    optionDisabled?: string | undefined;
    optionGroupLabel?: string | undefined;
    optionGroupChildren?: string;
    showHeader?: boolean;
    filterBy?: string | undefined;
    scrollHeight?: string;
    lazy?: boolean;
    virtualScroll?: boolean | undefined;
    loading?: boolean | undefined;
    virtualScrollItemSize?: number | undefined;
    loadingIcon?: string | undefined;
    virtualScrollOptions?: ScrollerOptions | undefined;
    overlayOptions?: OverlayOptions | undefined;
    ariaFilterLabel?: string | undefined;
    filterMatchMode?: 'contains' | 'startsWith' | 'endsWith' | 'equals' | 'notEquals' | 'in' | 'lt' | 'lte' | 'gt' | 'gte';
    tooltip?: string;
    tooltipPosition?: 'top' | 'left' | 'right' | 'bottom';
    tooltipPositionStyle?: string;
    tooltipStyleClass?: string | undefined;
    autofocusFilter?: boolean;
    display?: string | 'comma' | 'chip';
    autocomplete?: string;
    showClear?: boolean;
    autofocus?: boolean | undefined;
    focusOnHover?: boolean;
    filterFields?: unknown[] | undefined;
    selectOnFocus?: boolean;
    autoOptionFocus?: boolean;

    [key: string]: unknown;
}